name: Orebfuscator
main: lishid.orebfuscator.Orebfuscator
version: 1.0.0
author: lishid
description: >
             This plugin obfuscates data that is sent to players to prevent x-ray.
commands:
  ofc:
    description: Manage Orebfuscator.
    usage: |
           /<command> engine <1/2> - Set engine mode to 1 or 2
           /<command> threads - Set number of processing threads allowed
           /<command> updateradius - Set block update radius
           /<command> initialradius - Set initial obfuscation radius
           /<command> <enable/disable> - enable/disable ore obfuscation
           /<command> <enable/disable> <updatebreak|updatedamage>
           /<command> <enable/disable> <updatephysics|updateexplosion>
           /<command> <enable/disable> <darknesshide> - no light obfuscate
           /<command> <enable/disable> <op|perms> - op/permissions
           /<command> <enable/disable> world <worldname>
           /<command> reload - Reload from config file
           /<command> status - Show status of Orebfuscator