name: Orebfuscator
main: lishid.orebfuscator.Orebfuscator
version: '${project.version}'
author: lishid
softdepend: [Spout]
load: startup
description: >
             Modify chunk packets sent to players to prevent x-ray by replacing ores and other valuables.
commands:
  ofc:
    description: Manage Orebfuscator.
    usage: |
           /<command> engine <1/2> - Set engine mode to 1 or 2
           /<command> initialradius [number] - Set block initial radius
           /<command> updateradius [number] - Set block update radius
           /<command> threads [number] - Set allowed processing threads
           /<command> proximity [number] - Set ProximityHider distance
           /<command> <enable/disable> - Change the state of the plugin
           /<command> <enable/disable> <darknesshide> - DarknessObfuscate
           /<command> <enable/disable> <op|perms> - Ops/Permissions
           /<command> <enable/disable> updatethread - Toggle update thread
           /<command> <enable/disable> proximity - ProximityHider
           /<command> <enable/disable> cache - Chunk caching
           /<command> <enable/disable> verbose - Verbose mode
           /<command> <enable/disable> world <worldname>
           /<command> reload - Reload from config file
           /<command> status - Show status of Orebfuscator
           /<command> clearcache - Clear all cache
           /<command> recache - Clear the cache at current chunk
  chunk:
    description: Re-send chunks.
    usage: |
           /<command> [radius=2] Send the chunks within a specific radius