name: Orebfuscator
main: lishid.orebfuscator.Orebfuscator
version: 0.9.3
author: lishid
description: >
             This plugin obfuscates data that is sent to players to prevent x-ray.
commands:
  ofc:
    description: Manage Orebfuscator.
    usage: |
           /<command> engine <1|2> - Set engine mode to 1 or 2
           /<command> reload - Reload from config file
           /<command> enable
           /<command> disable
           /<command> status - Show status of Orebfuscator