api-version: 1.13

name: Orebfuscator
version: ${project.version}

main: net.imprex.orebfuscator.Orebfuscator

author: Ingrim4
authors: [NgLoader, lishid, SydMontague, ProgrammerDan, Aleksey-Terzi]

depend: [ProtocolLib]
loadbefore: [ProtocolLib]

load: POSTWORLD

description: 'High-Performance Anti X-Ray'

permissions:
  orebfuscator.admin:
    default: true
  orebfuscator.bypass:
    description: Bypass obfuscation
    default: false
